name: Qt CMake Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, prod]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      run: |
        cd build
        cmake -G Ninja .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=$Qt6_DIR \
          -DCMAKE_INSTALL_PREFIX=../install
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --parallel $(nproc)
